### PR TITLE
Make it work with psc-0.9.1

### PR DESCRIPTION
**Pull request by eskimor**
It depends on some PRs to other packages which are not yet merged.

### CODE REVIEW

**Comment by eskimor** [comment]
To be precise:
https://github.com/purescript-contrib/purescript-dom/pull/53 - already merged
https://github.com/zudov/purescript-var/pull/2

**Comment by eskimor** [comment]
@zudov only the PR for zudov/purescript-var is missing. Then this PR should be fine.

**Comment by adarqui** [comment]
I need this (and purescript-var) too. Thanks @eskimor.

**Comment by eskimor** [comment]
@adarqui You are welcome ;-)

**Comment by eskimor** [comment]
ping @zudov can this be merged?

**Comment by zudov** [comment]
Looks good and builds fine. CI still fails due to not bumped dependencies in `example/bower.json`, but I can fix that once it's merged.

Thanks a lot for help with that, and sorry that I don't keep track of such things.

**Pull request merged**
